set nocompatible              " be iMproved, required
filetype plugin on
syntax on

set autowrite
set wildmenu

set smartindent

set undolevels=1000

if !isdirectory($HOME . "/.vim/undo")
  call mkdir($HOME . "/.vim/undo", "p", 0700)
endif

set undodir=~/.vim/undo
set undofile

set title

if executable('rg')
  set grepprg=rg\ --vimgrep
endif

nnoremap K :vimgrep! "<C-R><C-W>" **/*<CR>
"nnoremap K :grep! "<C-R><C-W>"<CR>

" Plugin configuration for https://github.com/natebosch/vim-lsc
let g:lsc_auto_map = v:true
let g:lsc_server_commands = {
  \ 'haskell': 'hie',
\}
