# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    "cryptkey" = { device = "/dev/disk/by-uuid/95405253-a1ac-45ae-a269-18f7b8f1fdc8"; };
    "cryptroot" = {
      device = "/dev/disk/by-uuid/d7bce135-59aa-42b9-8980-4b2d6bbf252b";
      keyFile = "/dev/mapper/cryptkey";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9de3e6a3-ed15-4930-a537-fc19bd22a516";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E680-647B";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
