[username]
disabled = false

[hostname]
disabled = false

[kubernetes]
disabled = true

[directory]
disabled = false

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[hg_branch]
disabled = true

[docker_context]
disabled = true

[package]
disabled = false

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true # too slow!

[java]
disabled = true

[julia]
disabled = true

[nodejs]
disabled = false

[php]
disabled = true

[python]
disabled = false

[ruby]
disabled = true

[rust]
disabled = false

[terraform]
disabled = true

[nix_shell]
disabled = false

[conda]
disabled = true

[memory_usage]
disabled = false

[aws]
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[cmd_duration]
disabled = false

[custom]
disabled = true

[line_break]
disabled = false

[jobs]
disabled = false

[battery]
disabled = false

[time]
disabled = false

[character]
disabled = false
